### ISSUE TITLE
Push notifications not showing on android

### ISSUE THREAD

**Issue by ifeanyi-earnipay** [customerio/customerio-flutter#64]
Whenever i try to send a Broadcast push notification to an android device, it doesn’t show up on the device. This works perfectly for iOS and when i send test push notifications to the same android device.

I'm using: 
- customer_io 1.2.2
- flutter 3.0.5

**Comment by ifeanyi-earnipay** [comment]
<img width="537" alt="Screenshot 2023-07-20 at 19 53 45" src="https://github.com/customerio/customerio-flutter/assets/109217810/d531bd32-c86d-4b0b-91e1-272dab50e4a5">

Test push notification to android device. This works.

**Comment by mrehan27** [comment]
Thank you for reaching out to us @ifeanyi-earnipay. We apologize for any inconvenience you're facing. To assist us in investigating further, please provide the following information:

1. Can you confirm the status of notifications sent from your campaign? Are they marked as `Delivered` but not received on your Android device?
2. Are you using Rich Push or Custom Payload? Can you please share sample payload?
3. Could you please confirm the state of your app when the notification is being sent from the dashboard? Try running the campaign with the app in Opened, Background, and Killed states to observe the behavior.
4. Please [collect and provide logs](https://www.customer.io/docs/sdk/flutter/updates-and-troubleshooting/troubleshooting/#capture-logs) when the notification is expected to arrive on your device. This will help us identify any errors if received.

To minimize any uncertainties, please ensure the following::

1. Confirm that the connectivity is fine on your Android device.
2. Test using another Android device to check if the issue persists.
3. If the problem persists, kindly share the details of the Android device you are currently using (model, OS version, etc.).

Please ensure that any sensitive information is removed from the logs/payload before sharing. Alternatively, you can email us the details at win@customer.io.

Once we have this information, we'll do our best to identify and resolve the problem. Thank you for your cooperation.

**Comment by ifeanyi-earnipay** [comment]
> Thank you for reaching out to us @ifeanyi-earnipay. We apologize for any inconvenience you're facing. To assist us in investigating further, please provide the following information:
> 
> 1. Can you confirm the status of notifications sent from your campaign? Are they marked as `Delivered` but not received on your Android device?
> 2. Are you using Rich Push or Custom Payload? Can you please share sample payload?
> 3. Could you please confirm the state of your app when the notification is being sent from the dashboard? Try running the campaign with the app in Opened, Background, and Killed states to observe the behavior.
> 4. Please [capture and share logs](https://www.customer.io/docs/sdk/flutter/updates-and-troubleshooting/troubleshooting/#capture-logs) when the notification is expected to arrive on your device. This will help us identify any errors if received.
> 
> To minimize any uncertainties, please ensure the following::
> 
> 1. Confirm that you have granted notification permission on your Android device for the app.
> 2. Confirm that the connectivity is fine on your Android device.
> 3. Test using another Android device to check if the issue persists.
> 4. If the problem persists, kindly share the details of the Android device you are currently using (model, OS version, etc.).
> 
> Please ensure that any sensitive information is removed from the logs/payload before sharing. Alternatively, you can email us the details at [win@customer.io](mailto:win@customer.io).
> 
> Once we have this information, we'll do our best to identify and resolve the problem. Thank you for your cooperation.

1. Yes, they're marked as `Delivered`
2. I'm using Rich Push. 
3. I've sent in background, foreground and killed state. It still doesn’t come through.
4. 
<img width="632" alt="Screenshot 2023-07-21 at 09 16 14" src="https://github.com/customerio/customerio-flutter/assets/109217810/11c3bc23-6407-4892-81fa-8ec64eb45163">

For uncertainties;
1. Notification permission is granted because I get test notifications.
2. Connectivity is fine.
3. Already tested.
4. 
<img width="828" alt="Screenshot 2023-07-21 at 09 20 23" src="https://github.com/customerio/customerio-flutter/assets/109217810/c37e87a4-5cf7-4951-a010-358af28c4066">

**Comment by mrehan27** [comment]
Thank you for sharing additional details. I noticed that you have `FirebaseMessaging` added to your project as well, and that might be the source of the issue. It appears that the notification is being received by the app, as confirmed by the log message `broadcast received for message`, but the app is unable to process it correctly.

To better assist you, could you please confirm if you have followed the instructions for handling multiple push providers, as suggested in [our documentation](https://www.customer.io/docs/sdk/flutter/push-notifications/multiple-push-providers/)? If you have, please confirm the option you chose and provide a code snippet for implementing it so that we can investigate further and offer you more specific assistance. This will help us pinpoint the potential problem and find a suitable solution.

**Comment by ifeanyi-earnipay** [comment]
Thank you @mrehan27. If i decide to use customer io to handle al my notifications need, can I completely remove `FirebaseMessaging` from the project entirely?

**Comment by mrehan27** [comment]
@ifeanyi-earnipay Yes, if you decide to use `Customer.io` to handle all your notifications, and you don't need to use any specific methods from `FirebaseMessaging`, you can safely remove `FirebaseMessaging` from your project entirely. Our SDK doesn't rely directly on `FirebaseMessaging` for Flutter, so it won't affect the functionality of our notification system.

I'm glad we could assist you with the resolution. Considering that the solution meets the expectations, I will proceed to close this issue. If you encounter any other problems or require further assistance, please don't hesitate to reopen this or open a new issue, or reach out to us. We appreciate your cooperation. Thank you!

**Comment by ifeanyi-earnipay** [comment]
Is there a customer io method to handle notification clicks like `FirebaseMessaging.onMessageOpenedApp` and `_firebaseMessaging.getInitialMessage()` does? @mrehan27

**Comment by mrehan27** [comment]
@ifeanyi-earnipay Unfortunately, no, the `Customer.io` SDK does not currently have direct methods like `FirebaseMessaging.onMessageOpenedApp` or `_firebaseMessaging.getInitialMessage()`. If you have a specific use case where such functionality would be beneficial, please provide more details, and I'll add a vote to the feature request internally on your behalf. This will help us prioritize the request and consider it for future updates. Your input is valuable, and we appreciate your engagement. Thank you!

**Comment by ifeanyi-earnipay** [comment]
@mrehan27 i want to be able to direct users to different parts of the app depending on the notifications they click.

**Comment by mrehan27** [comment]
@ifeanyi-earnipay Thank you for sharing your use case. Have you considered using deep links to direct users to different parts of the app when they click on notifications?

Regarding the app restart behavior, it is indeed intended. However, I will +1 the internal feature request for you so that we can prioritize the implementation of this feature.

**Comment by ifeanyi-earnipay** [comment]
@mrehan27 deep links will only work on direct users in the app, I also want to be able to direct users to the app on app/play stores when they click the link or to a website. With `FirebaseMessaging`, I was able to pass a custom payload, interpret it in the app and direct the user outside the app; to their respective stores or to a particular website.

**Comment by ifeanyi-earnipay** [comment]
Also @mrehan27, I noticed that notifications aren’t coming through when the app isn’t on foreground or background (when the app is killed/closed).

**Comment by mrehan27** [comment]
@ifeanyi-earnipay Thank you for clarifying your requirements. Your use case makes sense. I will +1 the internal feature request on your behalf.

Regarding notifications not coming through when the app is in the background, to help troubleshoot the problem, could you please check the following:

1. Ensure that you have implemented the `_firebaseMessagingBackgroundHandler` as suggested by the [Firebase Messaging documentation](https://firebase.google.com/docs/cloud-messaging/flutter/receive#background_messages). This handler is responsible for processing messages received while the app is in the background or closed.
2. Verify that the handler is set correctly and receiving callbacks. Double-check the implementation to ensure it's properly registered within your app's code.
3. Confirm the Flutter version you are using. You mentioned using Flutter 3.0.5 earlier, so please reverify the version. For Flutter version 3.3.0 or higher, you will need to add `@pragma('vm:entry-point')` to the handler function for it to work correctly.
4. To investigate the issue further, could you please [capture and share the relevant logs](https://www.customer.io/docs/sdk/flutter/updates-and-troubleshooting/troubleshooting/#capture-logs) again?

**Comment by ifeanyi-earnipay** [comment]
@mrehan27 everything works now, thanks. When should i expect to here news concerning the requirements i raised?

**Comment by mrehan27** [comment]
@ifeanyi-earnipay Glad to hear that your issue has been resolved successfully.

Regarding your feature request, we appreciate your input and have created an internal ticket to track it. However, I currently can't provide a specific estimate for its implementation as it is not yet on our roadmap, and features with higher requests may receive higher priority. Rest assured, your request is being considered, and we'll keep you updated on any developments. Your original issue has been linked with an internal ticket, so you'll be informed about its progress.

Thank you for your understanding and for sharing your thoughts. Your feedback is highly valuable to us. If you have any more ideas or feedback, do not hesitate to share them with us. Have a great day!

**Comment by mingjunsiek** [comment]
Please add a +1 for me as well regarding handling notification clicks with FirebaseMessaging.onMessageOpenedApp and _firebaseMessaging.getInitialMessage. This is a major feature that is still missing from CIO. I've just tried to update the package to the latest version and suddenly i lost the functionality of both FirebaseMessaging.onMessageOpenedApp and _firebaseMessaging.getInitialMessage because CIO SDK took over.
